/* -*- Mode: IDL; indent-tabs-mode: nil; c-basic-offset: 2 -*-
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

interface nsIOutputStream;
interface nsIWebBrowserPersistResourceVisitor;

interface nsIWebBrowserPersistDocument : nsISupports
{
  readonly attribute boolean isPrivate;
  readonly attribute ACString documentURI;
  readonly attribute ACString baseURI;
  readonly attribute ACString contentType;
  readonly attribute ACString charSet;
  // Is this right? Size estimates? Completion?
  void writeContent(in nsIOutputStream aStream /* FIXME needs URL map */);
  void readResources(in nsIWebBrowserPersistResourceVisitor aVisitor);
}

interface nsIWebBrowserPersistResourceVisitor : nsISupports
{
  void visitURI(in nsIWebBrowserPersistDocument aDocument,
                in ACString aURI, in ACString aContentType); // ???
  void visitDocument(in nsIWebBrowserPersistDocument aDocument,
                     in nsIWebBrowserPersistDocument aSubDocument, in aCString name); // ???
  void endVisit();
}

interface nsIWebBrowserPersistable : nsISupports
{
  nsIWebBrowserPersistDocument startPersistence();
}
