/* -*- Mode: IDL; indent-tabs-mode: nil; c-basic-offset: 2 -*-
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

interface nsIOutputStream;
interface nsIWebBrowserPersistResourceVisitor;

[scriptable, uuid(74aa4918-5d15-46b6-9ccf-74f9696d721d)]
interface nsIWebBrowserPersistDocument : nsISupports
{
  readonly attribute boolean isPrivate;
  readonly attribute ACString documentURI;
  readonly attribute ACString baseURI;
  readonly attribute ACString contentType;
  readonly attribute ACString charSet;
  // Is this right? Size estimates? Completion?
  void writeContent(in nsIOutputStream aStream,
                    in unsigned long aNumMappedURIs,
                    [array, size_is(aNumMappedURIs)] in ACString aMappedURIs,
                    [array, size_is(aNumMappedURIs)] in ACString aMapURIsTo);
  void readResources(in nsIWebBrowserPersistResourceVisitor aVisitor);
};

[scriptable, uuid(8ce37706-b7d3-481a-be68-54f174fc0d0a)]
interface nsIWebBrowserPersistResourceVisitor : nsISupports
{
  void visitURI(in nsIWebBrowserPersistDocument aDocument,
                in ACString aURI, in ACString aContentType); // ???
  void visitDocument(in nsIWebBrowserPersistDocument aDocument,
                     in nsIWebBrowserPersistDocument aSubDocument,
                     in ACString name); // ???
  void endVisit();
};

[scriptable, uuid(9e2d647a-a079-4d9a-90b2-565996cbd828)]
interface nsIWebBrowserPersistable : nsISupports
{
  nsIWebBrowserPersistDocument startPersistence();
};
