/* -*- Mode: IDL; indent-tabs-mode: nil; c-basic-offset: 2 -*-
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

interface nsIOutputStream;
interface nsIWebBrowserPersistResourceVisitor;

[scriptable, uuid(d52e8b93-2771-45e8-a5b0-6e12b667046b)]
interface nsIWebBrowserPersistMap : nsISupports
{
  readonly attribute unsigned long numMappedURIs;
  void getURIMapping(in unsigned long aIndex,
                     out AUTF8String aMapFrom,
                     out AUTF8String aMapTo);
};

[scriptable, uuid(74aa4918-5d15-46b6-9ccf-74f9696d721d)]
interface nsIWebBrowserPersistDocument : nsISupports
{
  readonly attribute boolean isPrivate;
  readonly attribute AUTF8String documentURI;
  readonly attribute AUTF8String baseURI;
  readonly attribute ACString contentType;
  readonly attribute ACString charSet;
  void readResources(in nsIWebBrowserPersistResourceVisitor aVisitor,
                     in unsigned long persistFlags);
  // Is this right? Size estimates? Completion?
  void writeContent(in nsIOutputStream aStream,
                    in nsIWebBrowserPersistMap aURIMap);
};

[scriptable, uuid(8ce37706-b7d3-481a-be68-54f174fc0d0a)]
interface nsIWebBrowserPersistResourceVisitor : nsISupports
{
  void visitURI(in nsIWebBrowserPersistDocument aDocument,
                in AUTF8String aURI);
  void visitDocument(in nsIWebBrowserPersistDocument aDocument,
                     in nsIWebBrowserPersistDocument aSubDocument);
  void endVisit(in nsIWebBrowserPersistDocument aDocument,
                in nsresult aStatus);
};
